name: BC Check

on: [push, pull_request]

jobs:
  roave-bc-check:
    name: Roave BC Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga
