name: BC Check

on: [push, pull_request]

jobs:
  roave-bc-check:
    name: Roave BC Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Roave BC Check
        uses: "addnab/docker-run-action@v3"
        with:
          image: "nyholm/roave-bc-check-ga"
          options: "--env GITHUB_REPOSITORY=${{ github.repository }} --user 1001 --volume ${{ github.workspace }}:/app"
          run: "/entrypoint.sh"
